# https://www.rutschmann.biz/de-de/typo3-blog/detail/typo3-mit-solr-und-nginx-mittels-docker-compose-auf-auf-amazon-ec2#c542
# https://medium.com/@tech_18484/deploying-a-php-web-app-with-docker-compose-nginx-and-mariadb-d61a84239c0d
# https://blog.hdnet.de/blog/setting-up-typo3-9-locally
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/php:8
    volumes:
      - ../..:/workspaces:cached
    networks:
      - frontend
      - backend
    command: sleep infinity
networks:
  frontend:
    # Specify driver options
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"
  backend: