name: Publish to TYPO3 TER
run-name: Publish new release to TER (on new release)

#run automatically when a new release is done
on:
  release:
    types: [published]

jobs:
  call_publish_workflow:
    uses: ./.github/workflows/reusable-publish.yml
    with:
      github-ref: ${{ github.ref }}
