name: Publish to TYPO3 TER

on:
  workflow_call:
    inputs:
      github-ref:
        required: true
        type: string

jobs:
  publish:
    name: Publish new version to TER
    runs-on: ubuntu-latest
    env:
      TYPO3_API_TOKEN: ${{ secrets.TYPO3_API_TOKEN }}
      TYPO3_API_USERNAME: ${{ secrets.TYPO3_API_USERNAME }}
      TYPO3_API_PASSWORD: ${{ secrets.TYPO3_API_PASSWORD }}

    steps:
      - name: Check auth credential preconditions
        run: |
          if [[ -z "${TYPO3_API_TOKEN}" || ( -z "${TYPO3_API_USERNAME}" || -z "${TYPO3_API_PASSWORD}" ) ]]; then
            echo "### :boom: Missing secret `TYPO3_API_TOKEN`" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo 'You may create a new token in ["My TYPO3"](https://extensions.typo3.org/my-access-tokens/create) backend.' >> $GITHUB_STEP_SUMMARY
            echo "Secrets `TYPO3_API_USERNAME`/`TYPO3_API_PASSWORD` are also allowed but discouraged." >> $GITHUB_STEP_SUMMARY
            echo "::error missing secret TYPO3_API_TOKEN or TYPO3_API_USERNAME/TYPO3_API_PASSWORD"
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set reference fom call
        run: |
          echo "INPUT_GITHUBREF=${{ inputs.github-ref }}" >> $GITHUB_ENV

      - name: Check tag
        run: |
          echo ${INPUT_GITHUBREF}
          # use ^refs/tags/v[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}$ when tag is prefixed with v
          if ! [[ ${INPUT_GITHUBREF} =~ ^refs/tags/v?[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}$ ]]; then
            exit 1
          fi

      - name: Get version
        id: get-version
        run: |
          echo INPUT_GITHUBREF="${INPUT_GITHUBREF}"
          echo "GIT_TAG=$(echo ${INPUT_GITHUBREF/refs\/tags\//})" >> $GITHUB_ENV
          # strip possibly trailing "v" from version
          echo "T3EXT_VERSION=$(echo ${INPUT_GITHUBREF/refs\/tags\//} | sed -r 's/^v(.*)/\1/')" >> $GITHUB_ENV

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: intl, mbstring, json, zip, curl
          tools: composer:v2

      - name: Install tailor
        run: composer global require typo3/tailor --prefer-dist --no-progress --no-suggest

      - name: Set TYPO3_EXTENSION_KEY from file
        run: |
          echo "TYPO3_EXTENSION_KEY=$(composer config extra.typo3/cms.extension-key)" >> $GITHUB_ENV

      - name: Set extension version
        run: php ~/.composer/vendor/bin/tailor set-version --no-docs -- ${{env.T3EXT_VERSION}}

      - name: Publish to TER
        run: |
          # upload using given tag annotations if some were given
          git tag -n10 -l ${INPUT_GITHUBREF} | sed 's/^[0-9.]*[ ]*//g' > RELEASE_NOTES
          if [[ $(wc -l RELEASE_NOTES|cut -d\  -f1) -eq 0 ]]; then
            # otherwise upload using reference to Github release
            echo "Updated extension to version ${T3EXT_VERSION}" > RELEASE_NOTES
            echo $'\nDetails see Github release notes:' >> RELEASE_NOTES
            echo "https://github.com/${{ github.repository }}/releases/tag/${{env.GIT_TAG}}" >> RELEASE_NOTES
          fi
          cat RELEASE_NOTES
          php ~/.composer/vendor/bin/tailor ter:publish --comment "$(cat RELEASE_NOTES)" ${{env.T3EXT_VERSION}}
  doxygen:
    name: Update Doxygen content on Github pages
    runs-on: ubuntu-latest

    steps:
      # Check statuses of Github
      - name: Check GitHub Pages status
        uses: crazy-max/ghaction-github-status@v4
        with:
          pages_threshold: major_outage

      - name: Checkout Code
        if: success()
        uses: actions/checkout@v4
        with:
          path: source

      - name: Create Doxygen target directory
        run: mkdir -p ${GITHUB_WORKSPACE}/target

      - name: Generate Doxygen
        if: success()
        uses: mattnotmitt/doxygen-action@v1
        with:
          working-directory: /github/workspace/target
          doxyfile-path: /github/workspace/source/.doxygen

      - name: Deploy Doxygen
        if: success()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/html
          keep_files: false
          commit_message: Update Doxygen for new release