name: Execute code tests
run-name: Execute code tests

#run automatically when a new release is done
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Execute code tests

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        typo3: [ ^12.4, ^13.4 ]
        php: [ '8.1', '8.2', '8.3' ]
        include:
          - typo3: ^12.4
            php: '8.1'
          - typo3: ^12.4
            php: '8.2'
          - typo3: ^12.4
            php: '8.3'
          - typo3: ^13.4
            php: '8.1'
          - typo3: ^13.4
            php: '8.2'
          - typo3: ^13.4
            php: '8.3'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint PHP
        run: composer thucke:test:php:lint

      - name: CGL
        run: composer test::cgl

      - name: PHPStan Classes
        run: composer test:phpstan:classes
