
name: Manual test actions

#run automatically when a new release is done
on:
  workflow_dispatch:

jobs:
  testCi:
    name: Test following CI action steps
    runs-on: ubuntu-latest
    env:
      TYPO3_EXTENSION_KEY: ${{ secrets.TYPO3_EXTENSION_KEY }}
      TYPO3_API_TOKEN: ${{ secrets.TYPO3_API_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version
        id: get-version
        run: |
          echo "version=$(echo 'v0.0.1')" >> $GITHUB_ENV
          # strip possibly trailing "v" from version
          echo "t3version=$(echo 'v0.0.1'} | sed -r 's/^v(.*)/\1/')" >> $GITHUB_ENV


      - name: Fetch release details from current repository
        id: get_latest_release
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/releases/tags/${{ env.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      #see: https://trstringer.com/github-actions-multiline-strings/
      #substituting the %, \n, and \r characters
      - name: Store release body
        id: set-release-body
        run: |
          RELEASE_BODY="${RELEASE_BODY//'%'/'%25'}"
          RELEASE_BODY="${RELEASE_BODY//$'\n'/'%0A'}"
          RELEASE_BODY="${RELEASE_BODY//$'\r'/'%0D'}"
          echo "release_body=${RELEASE_BODY}" >> $GITHUB_ENV
        env:
          RELEASE_BODY: ${{ fromJson(steps.get_latest_release.outputs.data).body }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: intl, mbstring, json, zip, curl
          tools: composer:v2

      - name: Install tailor
        run: composer global require typo3/tailor --prefer-dist --no-progress --no-suggest

      - name: Set extension version
        run: |
          echo "php ~/.composer/vendor/bin/tailor set-version ${{ env.t3version }}"

      - name: Publish to TER
        run: echo "php ~/.composer/vendor/bin/tailor ter:publish --comment \"${release_body}\" ${{ env.t3version }}"
